language: bash
services:
- docker
script: true
sudo: required
before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash scripts/install.sh || bash scripts/install_pr.sh'
group: stable
dist: precise
os: linux
